server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: Modulith
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:tskhra_db}
    username: admin
    password: password # todo add to env + change
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/tskhra


keycloak:
  server-url: http://${KEYCLOAK_HOST:localhost}:8080
  realm: tskhra
  client-id: user-service
  client-secret: hiDfHEHBRbi6VuEPvBDirMecSqINIXit # todo add to env


